In [1]:
import quandl
import os
from dotenv import load_dotenv
import pandas as pd
import datetime as dt

In [2]:
load_dotenv()

True

In [3]:
quandle_api = os.getenv('QUANDL_KEY_PRJ')
quandl.ApiConfig.api_key = quandle_api

In [4]:
tickers = ['AMZN','PRTY','CPPRQ','ETSY','M','WMT']
dataset = 'SHARADAR/SF1'
dimension = 'ARQ'
date = '2018-03-31'

#sq_last_3yrs = quandl.get_table('SHARADAR/SF1', dimension = 'ARQ', calendardate = {'gte':'2018-03-31'}, ticker = 'SQ')

In [5]:
all_3yr_data = pd.DataFrame()

for i in tickers:
    all_3yr_data = all_3yr_data.append(quandl.get_table(dataset, dimension = dimension, calendardate = {'gte':date}, ticker = i))

all_3yr_data_filtered = all_3yr_data.filter(items = ['ticker','calendardate', 'currentratio', 'assets',  'assetsc', 'cashenq', 'liabilitiesc', 'debt' , 'debtc' , 'debtnc', 'revenue' , 'capex','intexp', 'ebit', 'optinc', 'netinc','net', 'equityusd', 'de', 'gp', 'eps'])
#'assetsavg', 'roa', 'roe'
all_3yr_data_filtered.reset_index(drop=True)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2020-09-30,1.108,282179000000,112969000000,101912000000,81518000000,0,81518000000,96145000000,-9808000000,428000000,7328000000,6331000000,82775000000,2.409,39039000000,12.63
1,AMZN,2020-06-30,1.181,258314000000,110908000000,93896000000,75926000000,0,75926000000,88912000000,-6615000000,403000000,6630000000,5243000000,73728000000,2.504,36252000000,10.50
2,AMZN,2020-03-31,1.079,221238000000,85985000000,79711000000,63737000000,0,63737000000,75452000000,-5428000000,402000000,3681000000,2535000000,65272000000,2.389,31195000000,5.09
3,AMZN,2019-12-31,1.097,225248000000,96334000000,87812000000,63205000000,0,63205000000,87436000000,-3940000000,455000000,4509000000,3268000000,62060000000,2.630,33459000000,6.59
4,AMZN,2019-09-30,1.096,199099000000,79054000000,72136000000,59530000000,0,59530000000,69981000000,-3385000000,396000000,3024000000,2134000000,56508000000,2.523,28679000000,4.31
5,AMZN,2019-06-30,1.102,191351000000,76790000000,69678000000,58463000000,0,58463000000,63404000000,-2643000000,383000000,3265000000,2625000000,53061000000,2.606,27067000000,5.32
6,AMZN,2019-03-31,1.090,178102000000,69431000000,63695000000,56597000000,0,56597000000,59700000000,-2721000000,366000000,4763000000,3561000000,48410000000,2.679,25780000000,7.24
7,AMZN,2018-12-31,1.098,162648000000,75101000000,68391000000,23495000000,0,23495000000,72383000000,-3120000000,387000000,3741000000,3027000000,43549000000,2.735,27597000000,6.19
8,AMZN,2018-09-30,1.082,143695000000,59885000000,55324000000,24684000000,0,24684000000,56576000000,-2527000000,358000000,3749000000,2883000000,39125000000,2.673,23573000000,5.91
9,AMZN,2018-06-30,1.072,134100000000,54481000000,50801000000,24638000000,0,24638000000,52886000000,-2949000000,343000000,2951000000,2534000000,34995000000,2.832,22254000000,5.21
10,AMZN,2018-03-31,1.058,126362000000,50829000000,48045000000,24640000000,0,24640000000,51042000000,-2727000000,330000000,2246000000,1629000000,31463000000,3.016,20307000000,3.36
11,PRTY,2020-09-30,1.187,3108009000,1062782000,895286000,2524233000,512712000,2011521000,533775000,-13688000,13422000,248965000,239707000,136399000,21.788,175057000,2.78
12,PRTY,2020-06-30,1.118,3056783000,968938000,866543000,2785401000,542535000,2242866000,254691000,-7606000,25412000,-128234000,-130015000,-136810000,-23.345,13663000,-1.39
13,PRTY,2020-03-31,1.150,3134795000,1017229000,884854000,2816212000,633624000,2182588000,414043000,-10719000,25120000,-616891000,-541513000,-19464000,-162.064,113977000,-5.80
14,PRTY,2019-12-31,1.287,3595319000,894130000,694927000,2580523000,355801000,2224722000,731551000,116477000,26042000,-222272000,-268818000,529745000,5.781,293090000,-2.89
15,PRTY,2019-09-30,1.248,4231797000,1210983000,970634000,2926472000,615295000,2311177000,540231000,-14625000,29424000,-279361000,-281533000,782428000,4.404,163544000,-3.02
16,PRTY,2019-06-30,1.225,4458969000,1042005000,850355000,2888393000,529102000,2359291000,563891000,95084000,30176000,94212000,48074000,1068876000,3.168,207599000,0.52
17,PRTY,2019-03-31,1.161,4397260000,1009984000,870132000,2880391000,554225000,2326166000,513116000,-12383000,29257000,-11480000,-30218000,1018855000,3.312,170771000,-0.32
18,PRTY,2018-12-31,1.439,3642347000,1023835000,711437000,1938030000,316067000,1621963000,805634000,-20137000,29225000,156878000,98318000,1043330000,2.488,361770000,1.02
19,PRTY,2018-09-30,1.304,3747381000,1125469000,863411000,2051619000,428650000,1622969000,553046000,-21084000,27705000,26070000,-2412000,994768000,2.764,202543000,-0.03
20,PRTY,2018-06-30,1.274,3532384000,941247000,738601000,1920831000,392568000,1528263000,561011000,-26500000,25501000,62948000,28077000,994386000,2.549,227554000,0.30
21,PRTY,2018-03-31,1.267,3472896000,884778000,698454000,1892751000,362532000,1530219000,507824000,-17885000,23275000,21438000,-1133000,973455000,2.564,187076000,-0.01
22,CPPRQ,2020-09-30,1.150,8134000000,3703000000,3221000000,7227000000,2164000000,5063000000,1758000000,-16000000,96000000,-271000000,-368000000,-475000000,-18.124,580000000,-1.13
23,CPPRQ,2020-06-30,1.218,8403000000,3838000000,3152000000,7154000000,2104000000,5050000000,1459000000,-10000000,67000000,-338000000,-398000000,-89000000,-95.416,540000000,-1.23
24,CPPRQ,2020-03-31,0.500,8223000000,3191000000,6376000000,6054000000,4968000000,1086000000,1196000000,-33000000,75000000,-531000000,-546000000,348000000,22.629,383000000,-1.69
25,CPPRQ,2019-12-31,1.411,7989000000,2726000000,1932000000,4897000000,215000000,4682000000,3493000000,-83000000,73000000,98000000,27000000,829000000,8.637,1236000000,0.08
26,CPPRQ,2019-09-30,1.515,8699000000,3376000000,2229000000,5349000000,225000000,5124000000,2500000000,-80000000,73000000,-21000000,-93000000,868000000,9.022,959000000,-0.29
27,CPPRQ,2019-06-30,1.372,8260000000,2921000000,2129000000,4960000000,281000000,4679000000,2619000000,-75000000,74000000,31000000,-48000000,963000000,7.577,1034000000,-0.15
28,CPPRQ,2019-03-31,1.509,8342000000,2935000000,1945000000,5087000000,178000000,4909000000,2555000000,-71000000,73000000,-80000000,-154000000,1034000000,7.068,925000000,-0.48
29,CPPRQ,2018-12-31,1.524,7721000000,2959000000,1942000000,4020000000,100000000,3920000000,3786000000,-71000000,78000000,141000000,75000000,1170000000,5.599,1267000000,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,ETSY,2019-12-31,4.885,1542352000,921038000,188528000,847012000,8275000,838737000,269998000,-3147000,9912000,32663000,31291000,406634000,2.793,179174000,0.26
37,ETSY,2019-09-30,6.114,1499198000,945840000,154707000,840473000,8770000,831703000,197947000,-3715000,5077000,15166000,14801000,389262000,2.851,128998000,0.12
38,ETSY,2019-06-30,4.466,1021775000,743653000,166510000,350726000,9306000,341420000,181095000,-4343000,4678000,21047000,18223000,442301000,1.310,122490000,0.15
39,ETSY,2019-03-31,4.870,981168000,724001000,148675000,349763000,9927000,339836000,169339000,-4073000,4653000,36090000,31579000,420013000,1.336,116681000,0.26
40,ETSY,2018-12-31,6.071,901851000,680289000,112062000,342456000,3884000,338572000,200028000,-6440000,6154000,29030000,41251000,400898000,1.250,142917000,0.34
41,ETSY,2018-09-30,5.491,907368000,707949000,128931000,339873000,4284000,335589000,150366000,-5666000,6135000,20731000,19894000,394619000,1.299,103419000,0.17
42,ETSY,2018-06-30,5.870,865310000,666233000,113499000,336340000,4376000,331964000,132387000,-5161000,6125000,10750000,3379000,370091000,1.338,86978000,0.03
43,ETSY,2018-03-31,6.616,870165000,704997000,106556000,333548000,4861000,328687000,120912000,-3289000,3764000,16745000,12967000,384487000,1.263,79617000,0.11
44,M,2020-09-30,1.106,19214000000,7357000000,6651000000,8654000000,536000000,8118000000,3990000000,-89000000,80000000,-137000000,-91000000,2243000000,7.566,1421000000,-0.29
45,M,2020-06-30,1.160,17614000000,5631000000,4854000000,8659000000,539000000,8120000000,3559000000,-119000000,70000000,-659000000,-431000000,2324000000,6.579,841000000,-1.39
46,M,2020-03-31,1.236,18581000000,7135000000,5772000000,8580000000,739000000,7841000000,3017000000,-139000000,49000000,-4108000000,-3581000000,2697000000,5.890,516000000,-11.53
47,M,2019-12-31,1.184,21172000000,6810000000,5750000000,7078000000,539000000,6539000000,8337000000,-233000000,46000000,495000000,340000000,6377000000,2.320,3071000000,1.10
48,M,2019-09-30,1.281,22547000000,8301000000,6479000000,7502000000,6000000,7496000000,5173000000,-297000000,52000000,52000000,2000000,6057000000,2.722,2067000000,0.01
49,M,2019-06-30,1.475,20741000000,6546000000,4439000000,7522000000,6000000,7516000000,5546000000,-212000000,52000000,168000000,86000000,6315000000,2.284,2151000000,0.28
50,M,2019-03-31,1.416,21296000000,7105000000,5019000000,7544000000,41000000,7503000000,5504000000,-230000000,54000000,217000000,136000000,6323000000,2.368,2101000000,0.44
51,M,2018-12-31,1.423,19194000000,7445000000,5232000000,4751000000,43000000,4708000000,8455000000,98000000,57000000,1023000000,740000000,6436000000,1.982,3167000000,2.40
52,M,2018-09-30,1.345,20361000000,8667000000,6444000000,5534000000,65000000,5469000000,5404000000,-236000000,64000000,138000000,62000000,5667000000,2.597,2178000000,0.20
53,M,2018-06-30,1.532,18668000000,6865000000,4481000000,5536000000,63000000,5473000000,5572000000,-153000000,69000000,268000000,166000000,5916000000,2.159,2252000000,0.54
54,M,2018-03-31,1.519,19568000000,7710000000,5077000000,5882000000,25000000,5857000000,5541000000,-167000000,71000000,262000000,139000000,5821000000,2.365,2159000000,0.45
55,WMT,2020-09-30,0.835,250863000000,73602000000,88121000000,68478000000,6897000000,61581000000,134708000000,-2853000000,541000000,7590000000,5135000000,81431000000,2.006,34369000000,1.81
56,WMT,2020-06-30,0.793,237382000000,64996000000,81957000000,69494000000,8193000000,61301000000,137742000000,-1794000000,658000000,9341000000,6476000000,75310000000,2.074,35053000000,2.29
57,WMT,2020-03-31,0.766,232892000000,63328000000,82647000000,75432000000,12283000000,63149000000,134622000000,-1692000000,592000000,5904000000,3990000000,68240000000,2.327,32596000000,1.41
58,WMT,2019-12-31,0.795,236495000000,61806000000,77790000000,72433000000,8241000000,64192000000,141671000000,-2837000000,652000000,6172000000,4141000000,74669000000,2.075,33923000000,1.46
59,WMT,2019-09-30,0.811,239830000000,67912000000,83784000000,75948000000,11227000000,64721000000,127991000000,-2804000000,633000000,4973000000,3288000000,71649000000,2.254,32091000000,1.16
60,WMT,2019-06-30,0.764,234861000000,61371000000,80283000000,74709000000,10311000000,64398000000,130377000000,-2580000000,641000000,5484000000,3610000000,70327000000,2.243,32454000000,1.27
61,WMT,2019-03-31,0.773,234544000000,61739000000,79888000000,75429000000,8475000000,66954000000,123925000000,-2163000000,673000000,5766000000,3842000000,68205000000,2.341,30891000000,1.34
62,WMT,2018-12-31,0.799,219295000000,61897000000,77477000000,58033000000,7830000000,50203000000,138793000000,-3119000000,669000000,6207000000,3687000000,72496000000,1.926,33886000000,1.27
63,WMT,2018-09-30,0.810,226583000000,69446000000,85751000000,60991000000,11095000000,49896000000,124894000000,-2629000000,593000000,3062000000,1710000000,71996000000,2.043,31778000000,0.58
64,WMT,2018-06-30,0.926,206062000000,66370000000,71683000000,53796000000,2228000000,51568000000,128028000000,-2457000000,554000000,818000000,-861000000,71185000000,1.858,32457000000,-0.29
65,WMT,2018-03-31,0.734,204927000000,59242000000,80757000000,46343000000,10038000000,36305000000,122690000000,-1620000000,530000000,3210000000,2134000000,75552000000,1.676,30983000000,0.72

In [6]:
#range = (all_3yr_data_filtered['calendardate'] < '2020-03-31') & (all_3yr_data_filtered['calendardate'] >= '2019-03-31')

all_yr1_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2019-03-31') & (all_3yr_data_filtered['calendardate'] >= '2018-03-31')]
all_yr1_data_filtered.reset_index(drop=True)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2018-12-31,1.098,162648000000,75101000000,68391000000,23495000000,0,23495000000,72383000000,-3120000000,387000000,3741000000,3027000000,43549000000,2.735,27597000000,6.19
1,AMZN,2018-09-30,1.082,143695000000,59885000000,55324000000,24684000000,0,24684000000,56576000000,-2527000000,358000000,3749000000,2883000000,39125000000,2.673,23573000000,5.91
2,AMZN,2018-06-30,1.072,134100000000,54481000000,50801000000,24638000000,0,24638000000,52886000000,-2949000000,343000000,2951000000,2534000000,34995000000,2.832,22254000000,5.21
3,AMZN,2018-03-31,1.058,126362000000,50829000000,48045000000,24640000000,0,24640000000,51042000000,-2727000000,330000000,2246000000,1629000000,31463000000,3.016,20307000000,3.36
4,PRTY,2018-12-31,1.439,3642347000,1023835000,711437000,1938030000,316067000,1621963000,805634000,-20137000,29225000,156878000,98318000,1043330000,2.488,361770000,1.02
5,PRTY,2018-09-30,1.304,3747381000,1125469000,863411000,2051619000,428650000,1622969000,553046000,-21084000,27705000,26070000,-2412000,994768000,2.764,202543000,-0.03
6,PRTY,2018-06-30,1.274,3532384000,941247000,738601000,1920831000,392568000,1528263000,561011000,-26500000,25501000,62948000,28077000,994386000,2.549,227554000,0.30
7,PRTY,2018-03-31,1.267,3472896000,884778000,698454000,1892751000,362532000,1530219000,507824000,-17885000,23275000,21438000,-1133000,973455000,2.564,187076000,-0.01
8,CPPRQ,2018-12-31,1.524,7721000000,2959000000,1942000000,4020000000,100000000,3920000000,3786000000,-71000000,78000000,141000000,75000000,1170000000,5.599,1267000000,0.24
9,CPPRQ,2018-09-30,1.576,8415000000,3615000000,2294000000,4467000000,100000000,4367000000,2733000000,-100000000,78000000,-81000000,-151000000,1074000000,6.835,925000000,-0.48
10,CPPRQ,2018-06-30,1.627,8058000000,3227000000,1984000000,4217000000,49000000,4168000000,2829000000,-115000000,79000000,-17000000,-101000000,1216000000,5.627,998000000,-0.32
11,CPPRQ,2018-03-31,1.729,8305000000,3352000000,1939000000,4401000000,49000000,4352000000,2671000000,-106000000,78000000,-1000000,-78000000,1315000000,5.316,959000000,-0.25
12,ETSY,2018-12-31,6.071,901851000,680289000,112062000,342456000,3884000,338572000,200028000,-6440000,6154000,29030000,41251000,400898000,1.250,142917000,0.34
13,ETSY,2018-09-30,5.491,907368000,707949000,128931000,339873000,4284000,335589000,150366000,-5666000,6135000,20731000,19894000,394619000,1.299,103419000,0.17
14,ETSY,2018-06-30,5.870,865310000,666233000,113499000,336340000,4376000,331964000,132387000,-5161000,6125000,10750000,3379000,370091000,1.338,86978000,0.03
15,ETSY,2018-03-31,6.616,870165000,704997000,106556000,333548000,4861000,328687000,120912000,-3289000,3764000,16745000,12967000,384487000,1.263,79617000,0.11
16,M,2018-12-31,1.423,19194000000,7445000000,5232000000,4751000000,43000000,4708000000,8455000000,98000000,57000000,1023000000,740000000,6436000000,1.982,3167000000,2.40
17,M,2018-09-30,1.345,20361000000,8667000000,6444000000,5534000000,65000000,5469000000,5404000000,-236000000,64000000,138000000,62000000,5667000000,2.597,2178000000,0.20
18,M,2018-06-30,1.532,18668000000,6865000000,4481000000,5536000000,63000000,5473000000,5572000000,-153000000,69000000,268000000,166000000,5916000000,2.159,2252000000,0.54
19,M,2018-03-31,1.519,19568000000,7710000000,5077000000,5882000000,25000000,5857000000,5541000000,-167000000,71000000,262000000,139000000,5821000000,2.365,2159000000,0.45
20,WMT,2018-12-31,0.799,219295000000,61897000000,77477000000,58033000000,7830000000,50203000000,138793000000,-3119000000,669000000,6207000000,3687000000,72496000000,1.926,33886000000,1.27
21,WMT,2018-09-30,0.810,226583000000,69446000000,85751000000,60991000000,11095000000,49896000000,124894000000,-2629000000,593000000,3062000000,1710000000,71996000000,2.043,31778000000,0.58
22,WMT,2018-06-30,0.926,206062000000,66370000000,71683000000,53796000000,2228000000,51568000000,128028000000,-2457000000,554000000,818000000,-861000000,71185000000,1.858,32457000000,-0.29
23,WMT,2018-03-31,0.734,204927000000,59242000000,80757000000,46343000000,10038000000,36305000000,122690000000,-1620000000,530000000,3210000000,2134000000,75552000000,1.676,30983000000,0.72

In [7]:
amzn_yr1_data = all_yr1_data_filtered.loc[all_yr1_data_filtered['ticker'] == 'AMZN']
amzn_yr1_data.reset_index(drop=True)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2018-12-31,1.098,162648000000,75101000000,68391000000,23495000000,0,23495000000,72383000000,-3120000000,387000000,3741000000,3027000000,43549000000,2.735,27597000000,6.19
1,AMZN,2018-09-30,1.082,143695000000,59885000000,55324000000,24684000000,0,24684000000,56576000000,-2527000000,358000000,3749000000,2883000000,39125000000,2.673,23573000000,5.91
2,AMZN,2018-06-30,1.072,134100000000,54481000000,50801000000,24638000000,0,24638000000,52886000000,-2949000000,343000000,2951000000,2534000000,34995000000,2.832,22254000000,5.21
3,AMZN,2018-03-31,1.058,126362000000,50829000000,48045000000,24640000000,0,24640000000,51042000000,-2727000000,330000000,2246000000,1629000000,31463000000,3.016,20307000000,3.36

In [8]:
all_yr2_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2020-03-31') & (all_3yr_data_filtered['calendardate'] >= '2019-03-31')]
all_yr2_data_filtered.reset_index(drop=True)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2019-12-31,1.097,225248000000,96334000000,87812000000,63205000000,0,63205000000,87436000000,-3940000000,455000000,4509000000,3268000000,62060000000,2.630,33459000000,6.59
1,AMZN,2019-09-30,1.096,199099000000,79054000000,72136000000,59530000000,0,59530000000,69981000000,-3385000000,396000000,3024000000,2134000000,56508000000,2.523,28679000000,4.31
2,AMZN,2019-06-30,1.102,191351000000,76790000000,69678000000,58463000000,0,58463000000,63404000000,-2643000000,383000000,3265000000,2625000000,53061000000,2.606,27067000000,5.32
3,AMZN,2019-03-31,1.090,178102000000,69431000000,63695000000,56597000000,0,56597000000,59700000000,-2721000000,366000000,4763000000,3561000000,48410000000,2.679,25780000000,7.24
4,PRTY,2019-12-31,1.287,3595319000,894130000,694927000,2580523000,355801000,2224722000,731551000,116477000,26042000,-222272000,-268818000,529745000,5.781,293090000,-2.89
5,PRTY,2019-09-30,1.248,4231797000,1210983000,970634000,2926472000,615295000,2311177000,540231000,-14625000,29424000,-279361000,-281533000,782428000,4.404,163544000,-3.02
6,PRTY,2019-06-30,1.225,4458969000,1042005000,850355000,2888393000,529102000,2359291000,563891000,95084000,30176000,94212000,48074000,1068876000,3.168,207599000,0.52
7,PRTY,2019-03-31,1.161,4397260000,1009984000,870132000,2880391000,554225000,2326166000,513116000,-12383000,29257000,-11480000,-30218000,1018855000,3.312,170771000,-0.32
8,CPPRQ,2019-12-31,1.411,7989000000,2726000000,1932000000,4897000000,215000000,4682000000,3493000000,-83000000,73000000,98000000,27000000,829000000,8.637,1236000000,0.08
9,CPPRQ,2019-09-30,1.515,8699000000,3376000000,2229000000,5349000000,225000000,5124000000,2500000000,-80000000,73000000,-21000000,-93000000,868000000,9.022,959000000,-0.29
10,CPPRQ,2019-06-30,1.372,8260000000,2921000000,2129000000,4960000000,281000000,4679000000,2619000000,-75000000,74000000,31000000,-48000000,963000000,7.577,1034000000,-0.15
11,CPPRQ,2019-03-31,1.509,8342000000,2935000000,1945000000,5087000000,178000000,4909000000,2555000000,-71000000,73000000,-80000000,-154000000,1034000000,7.068,925000000,-0.48
12,ETSY,2019-12-31,4.885,1542352000,921038000,188528000,847012000,8275000,838737000,269998000,-3147000,9912000,32663000,31291000,406634000,2.793,179174000,0.26
13,ETSY,2019-09-30,6.114,1499198000,945840000,154707000,840473000,8770000,831703000,197947000,-3715000,5077000,15166000,14801000,389262000,2.851,128998000,0.12
14,ETSY,2019-06-30,4.466,1021775000,743653000,166510000,350726000,9306000,341420000,181095000,-4343000,4678000,21047000,18223000,442301000,1.310,122490000,0.15
15,ETSY,2019-03-31,4.870,981168000,724001000,148675000,349763000,9927000,339836000,169339000,-4073000,4653000,36090000,31579000,420013000,1.336,116681000,0.26
16,M,2019-12-31,1.184,21172000000,6810000000,5750000000,7078000000,539000000,6539000000,8337000000,-233000000,46000000,495000000,340000000,6377000000,2.320,3071000000,1.10
17,M,2019-09-30,1.281,22547000000,8301000000,6479000000,7502000000,6000000,7496000000,5173000000,-297000000,52000000,52000000,2000000,6057000000,2.722,2067000000,0.01
18,M,2019-06-30,1.475,20741000000,6546000000,4439000000,7522000000,6000000,7516000000,5546000000,-212000000,52000000,168000000,86000000,6315000000,2.284,2151000000,0.28
19,M,2019-03-31,1.416,21296000000,7105000000,5019000000,7544000000,41000000,7503000000,5504000000,-230000000,54000000,217000000,136000000,6323000000,2.368,2101000000,0.44
20,WMT,2019-12-31,0.795,236495000000,61806000000,77790000000,72433000000,8241000000,64192000000,141671000000,-2837000000,652000000,6172000000,4141000000,74669000000,2.075,33923000000,1.46
21,WMT,2019-09-30,0.811,239830000000,67912000000,83784000000,75948000000,11227000000,64721000000,127991000000,-2804000000,633000000,4973000000,3288000000,71649000000,2.254,32091000000,1.16
22,WMT,2019-06-30,0.764,234861000000,61371000000,80283000000,74709000000,10311000000,64398000000,130377000000,-2580000000,641000000,5484000000,3610000000,70327000000,2.243,32454000000,1.27
23,WMT,2019-03-31,0.773,234544000000,61739000000,79888000000,75429000000,8475000000,66954000000,123925000000,-2163000000,673000000,5766000000,3842000000,68205000000,2.341,30891000000,1.34

In [9]:
all_yr3_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2021-03-31') & (all_3yr_data_filtered['calendardate'] >= '2020-03-31')]
all_yr3_data_filtered.reset_index(drop=True)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2020-09-30,1.108,282179000000,112969000000,101912000000,81518000000,0,81518000000,96145000000,-9808000000,428000000,7328000000,6331000000,82775000000,2.409,39039000000,12.63
1,AMZN,2020-06-30,1.181,258314000000,110908000000,93896000000,75926000000,0,75926000000,88912000000,-6615000000,403000000,6630000000,5243000000,73728000000,2.504,36252000000,10.50
2,AMZN,2020-03-31,1.079,221238000000,85985000000,79711000000,63737000000,0,63737000000,75452000000,-5428000000,402000000,3681000000,2535000000,65272000000,2.389,31195000000,5.09
3,PRTY,2020-09-30,1.187,3108009000,1062782000,895286000,2524233000,512712000,2011521000,533775000,-13688000,13422000,248965000,239707000,136399000,21.788,175057000,2.78
4,PRTY,2020-06-30,1.118,3056783000,968938000,866543000,2785401000,542535000,2242866000,254691000,-7606000,25412000,-128234000,-130015000,-136810000,-23.345,13663000,-1.39
5,PRTY,2020-03-31,1.150,3134795000,1017229000,884854000,2816212000,633624000,2182588000,414043000,-10719000,25120000,-616891000,-541513000,-19464000,-162.064,113977000,-5.80
6,CPPRQ,2020-09-30,1.150,8134000000,3703000000,3221000000,7227000000,2164000000,5063000000,1758000000,-16000000,96000000,-271000000,-368000000,-475000000,-18.124,580000000,-1.13
7,CPPRQ,2020-06-30,1.218,8403000000,3838000000,3152000000,7154000000,2104000000,5050000000,1459000000,-10000000,67000000,-338000000,-398000000,-89000000,-95.416,540000000,-1.23
8,CPPRQ,2020-03-31,0.500,8223000000,3191000000,6376000000,6054000000,4968000000,1086000000,1196000000,-33000000,75000000,-531000000,-546000000,348000000,22.629,383000000,-1.69
9,ETSY,2020-09-30,4.980,2214505000,1697831000,340942000,1110096000,8345000,1101751000,451478000,-1821000,10615000,101008000,91761000,666667000,2.322,331310000,0.75
10,ETSY,2020-06-30,4.272,1762031000,1194335000,279579000,860558000,8073000,852485000,428737000,-424000,10026000,122342000,96425000,524175000,2.362,317356000,0.81
11,ETSY,2020-03-31,5.710,1517642000,906952000,158849000,853587000,8000000,845587000,228055000,-1828000,9967000,19660000,12522000,406847000,2.730,145639000,0.11
12,M,2020-09-30,1.106,19214000000,7357000000,6651000000,8654000000,536000000,8118000000,3990000000,-89000000,80000000,-137000000,-91000000,2243000000,7.566,1421000000,-0.29
13,M,2020-06-30,1.160,17614000000,5631000000,4854000000,8659000000,539000000,8120000000,3559000000,-119000000,70000000,-659000000,-431000000,2324000000,6.579,841000000,-1.39
14,M,2020-03-31,1.236,18581000000,7135000000,5772000000,8580000000,739000000,7841000000,3017000000,-139000000,49000000,-4108000000,-3581000000,2697000000,5.890,516000000,-11.53
15,WMT,2020-09-30,0.835,250863000000,73602000000,88121000000,68478000000,6897000000,61581000000,134708000000,-2853000000,541000000,7590000000,5135000000,81431000000,2.006,34369000000,1.81
16,WMT,2020-06-30,0.793,237382000000,64996000000,81957000000,69494000000,8193000000,61301000000,137742000000,-1794000000,658000000,9341000000,6476000000,75310000000,2.074,35053000000,2.29
17,WMT,2020-03-31,0.766,232892000000,63328000000,82647000000,75432000000,12283000000,63149000000,134622000000,-1692000000,592000000,5904000000,3990000000,68240000000,2.327,32596000000,1.41

In [10]:
current_ratio = all_3yr_data_filtered.filter(items = ['ticker','calendardate','currentratio'])

debt_equity = all_3yr_data_filtered.filter(items = ['ticker','calendardate','de'])

In [11]:
def get_quarterly_data_by_year(year):
    all_3yr_data = pd.DataFrame()

    for i in tickers:
        all_3yr_data = all_3yr_data.append(quandl.get_table(dataset, dimension = dimension, calendardate = {'gte':date}, ticker = i))

    all_3yr_data_filtered = all_3yr_data.filter(items = ['ticker','calendardate', 'currentratio', 'assets',  'assetsc', 'cashenq', 'liabilitiesc', 'debt' , 'debtc' , 'debtnc', 'revenue' , 'capex','intexp', 'ebit', 'optinc', 'netinc','net', 'equityusd', 'de', 'gp', 'eps'])
    #'assetsavg', 'roa', 'roe'
    all_3yr_data_filtered = all_3yr_data_filtered.reset_index(drop=True)
    
    all_yr1_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2019-03-31') & (all_3yr_data_filtered['calendardate'] >= '2018-03-31')]
    all_yr1_data_filtered = all_yr1_data_filtered.reset_index(drop=True)
    
    all_yr2_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2020-03-31') & (all_3yr_data_filtered['calendardate'] >= '2019-03-31')]
    all_yr2_data_filtered = all_yr2_data_filtered.reset_index(drop=True)
    
    all_yr3_data_filtered = all_3yr_data_filtered.loc[(all_3yr_data_filtered['calendardate'] < '2021-03-31') & (all_3yr_data_filtered['calendardate'] >= '2020-03-31')]
    all_yr3_data_filtered = all_yr3_data_filtered.reset_index(drop=True)
    
    if year == 2018:
        return all_yr1_data_filtered
    elif year == 2019:
        return all_yr2_data_filtered
    else: 
        return all_yr3_data_filtered

    
def get_quarterly_data_by_year_ticker(year,ticker):
    
    yr_data_filtered = get_quarterly_data_by_year(year)
    
    ticker_yr1_data = yr_data_filtered.loc[yr_data_filtered['ticker'] == ticker]
    ticker_yr1_data = ticker_yr1_data.reset_index(drop=True)
    
    return ticker_yr1_data


def current_ratio_year(year):
    yr_data_filtered = get_quarterly_data_by_year(year)
    
    current_ratio_all = yr_data_filtered.filter(items = ['ticker','calendardate','currentratio'])
    
    return current_ratio_all


def current_ratio_ticker_year(ticker,year):
    yr_data_filtered = get_quarterly_data_by_year(year)
    
    current_ratio_all = yr_data_filtered.filter(items = ['ticker','calendardate','currentratio'])
    current_ratio_ticker = current_ratio_all.loc[current_ratio_all['ticker'] == ticker]
    
    return current_ratio_ticker


def debt_equity_year(year):
    yr_data_filtered = get_quarterly_data_by_year(year)
    
    debt_equity_all = yr_data_filtered.filter(items = ['ticker','calendardate','de'])
    
    return debt_equity_all


def debt_equity_ticker_year(ticker,year):
    yr_data_filtered = get_quarterly_data_by_year(year)
    
    debt_equity_all = yr_data_filtered.filter(items = ['ticker','calendardate','de'])
    debt_equity_ticker = debt_equity_all.loc[debt_equity_all['ticker'] == ticker]
    
    return debt_equity_ticker


# def current_ratio_ticker_col():
#     year = [2018,2019,2020]
#     amzn = {}
#     for y in year:
#         amzn[y] = current_ratio_ticker_year('AMZN',y)

In [44]:
get_quarterly_data_by_year(2019)

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2019-12-31,1.097,225248000000,96334000000,87812000000,63205000000,0,63205000000,87436000000,-3940000000,455000000,4509000000,3268000000,62060000000,2.630,33459000000,6.59
1,AMZN,2019-09-30,1.096,199099000000,79054000000,72136000000,59530000000,0,59530000000,69981000000,-3385000000,396000000,3024000000,2134000000,56508000000,2.523,28679000000,4.31
2,AMZN,2019-06-30,1.102,191351000000,76790000000,69678000000,58463000000,0,58463000000,63404000000,-2643000000,383000000,3265000000,2625000000,53061000000,2.606,27067000000,5.32
3,AMZN,2019-03-31,1.090,178102000000,69431000000,63695000000,56597000000,0,56597000000,59700000000,-2721000000,366000000,4763000000,3561000000,48410000000,2.679,25780000000,7.24
4,PRTY,2019-12-31,1.287,3595319000,894130000,694927000,2580523000,355801000,2224722000,731551000,116477000,26042000,-222272000,-268818000,529745000,5.781,293090000,-2.89
5,PRTY,2019-09-30,1.248,4231797000,1210983000,970634000,2926472000,615295000,2311177000,540231000,-14625000,29424000,-279361000,-281533000,782428000,4.404,163544000,-3.02
6,PRTY,2019-06-30,1.225,4458969000,1042005000,850355000,2888393000,529102000,2359291000,563891000,95084000,30176000,94212000,48074000,1068876000,3.168,207599000,0.52
7,PRTY,2019-03-31,1.161,4397260000,1009984000,870132000,2880391000,554225000,2326166000,513116000,-12383000,29257000,-11480000,-30218000,1018855000,3.312,170771000,-0.32
8,CPPRQ,2019-12-31,1.411,7989000000,2726000000,1932000000,4897000000,215000000,4682000000,3493000000,-83000000,73000000,98000000,27000000,829000000,8.637,1236000000,0.08
9,CPPRQ,2019-09-30,1.515,8699000000,3376000000,2229000000,5349000000,225000000,5124000000,2500000000,-80000000,73000000,-21000000,-93000000,868000000,9.022,959000000,-0.29
10,CPPRQ,2019-06-30,1.372,8260000000,2921000000,2129000000,4960000000,281000000,4679000000,2619000000,-75000000,74000000,31000000,-48000000,963000000,7.577,1034000000,-0.15
11,CPPRQ,2019-03-31,1.509,8342000000,2935000000,1945000000,5087000000,178000000,4909000000,2555000000,-71000000,73000000,-80000000,-154000000,1034000000,7.068,925000000,-0.48
12,ETSY,2019-12-31,4.885,1542352000,921038000,188528000,847012000,8275000,838737000,269998000,-3147000,9912000,32663000,31291000,406634000,2.793,179174000,0.26
13,ETSY,2019-09-30,6.114,1499198000,945840000,154707000,840473000,8770000,831703000,197947000,-3715000,5077000,15166000,14801000,389262000,2.851,128998000,0.12
14,ETSY,2019-06-30,4.466,1021775000,743653000,166510000,350726000,9306000,341420000,181095000,-4343000,4678000,21047000,18223000,442301000,1.310,122490000,0.15
15,ETSY,2019-03-31,4.870,981168000,724001000,148675000,349763000,9927000,339836000,169339000,-4073000,4653000,36090000,31579000,420013000,1.336,116681000,0.26
16,M,2019-12-31,1.184,21172000000,6810000000,5750000000,7078000000,539000000,6539000000,8337000000,-233000000,46000000,495000000,340000000,6377000000,2.320,3071000000,1.10
17,M,2019-09-30,1.281,22547000000,8301000000,6479000000,7502000000,6000000,7496000000,5173000000,-297000000,52000000,52000000,2000000,6057000000,2.722,2067000000,0.01
18,M,2019-06-30,1.475,20741000000,6546000000,4439000000,7522000000,6000000,7516000000,5546000000,-212000000,52000000,168000000,86000000,6315000000,2.284,2151000000,0.28
19,M,2019-03-31,1.416,21296000000,7105000000,5019000000,7544000000,41000000,7503000000,5504000000,-230000000,54000000,217000000,136000000,6323000000,2.368,2101000000,0.44
20,WMT,2019-12-31,0.795,236495000000,61806000000,77790000000,72433000000,8241000000,64192000000,141671000000,-2837000000,652000000,6172000000,4141000000,74669000000,2.075,33923000000,1.46
21,WMT,2019-09-30,0.811,239830000000,67912000000,83784000000,75948000000,11227000000,64721000000,127991000000,-2804000000,633000000,4973000000,3288000000,71649000000,2.254,32091000000,1.16
22,WMT,2019-06-30,0.764,234861000000,61371000000,80283000000,74709000000,10311000000,64398000000,130377000000,-2580000000,641000000,5484000000,3610000000,70327000000,2.243,32454000000,1.27
23,WMT,2019-03-31,0.773,234544000000,61739000000,79888000000,75429000000,8475000000,66954000000,123925000000,-2163000000,673000000,5766000000,3842000000,68205000000,2.341,30891000000,1.34

In [46]:
get_quarterly_data_by_year_ticker(2018,'AMZN')

,ticker,calendardate,currentratio,assets,assetsc,liabilitiesc,debt,debtc,debtnc,revenue,capex,intexp,ebit,netinc,equityusd,de,gp,eps
0,AMZN,2018-12-31,1.098,162648000000,75101000000,68391000000,23495000000,0,23495000000,72383000000,-3120000000,387000000,3741000000,3027000000,43549000000,2.735,27597000000,6.19
1,AMZN,2018-09-30,1.082,143695000000,59885000000,55324000000,24684000000,0,24684000000,56576000000,-2527000000,358000000,3749000000,2883000000,39125000000,2.673,23573000000,5.91
2,AMZN,2018-06-30,1.072,134100000000,54481000000,50801000000,24638000000,0,24638000000,52886000000,-2949000000,343000000,2951000000,2534000000,34995000000,2.832,22254000000,5.21
3,AMZN,2018-03-31,1.058,126362000000,50829000000,48045000000,24640000000,0,24640000000,51042000000,-2727000000,330000000,2246000000,1629000000,31463000000,3.016,20307000000,3.36

In [47]:
current_ratio_year(2019)

   ticker calendardate  currentratio
0    AMZN   2019-12-31         1.097
1    AMZN   2019-09-30         1.096
2    AMZN   2019-06-30         1.102
3    AMZN   2019-03-31         1.090
4    PRTY   2019-12-31         1.287
5    PRTY   2019-09-30         1.248
6    PRTY   2019-06-30         1.225
7    PRTY   2019-03-31         1.161
8   CPPRQ   2019-12-31         1.411
9   CPPRQ   2019-09-30         1.515
10  CPPRQ   2019-06-30         1.372
11  CPPRQ   2019-03-31         1.509
12   ETSY   2019-12-31         4.885
13   ETSY   2019-09-30         6.114
14   ETSY   2019-06-30         4.466
15   ETSY   2019-03-31         4.870
16      M   2019-12-31         1.184
17      M   2019-09-30         1.281
18      M   2019-06-30         1.475
19      M   2019-03-31         1.416
20    WMT   2019-12-31         0.795
21    WMT   2019-09-30         0.811
22    WMT   2019-06-30         0.764
23    WMT   2019-03-31         0.773

In [15]:
current_ratio_ticker_year('PRTY',2020)

  ticker calendardate  currentratio
3   PRTY   2020-09-30         1.187
4   PRTY   2020-06-30         1.118
5   PRTY   2020-03-31         1.150

In [17]:
debt_equity_year(2019)

   ticker calendardate     de
0    AMZN   2019-12-31  2.630
1    AMZN   2019-09-30  2.523
2    AMZN   2019-06-30  2.606
3    AMZN   2019-03-31  2.679
4    PRTY   2019-12-31  5.781
5    PRTY   2019-09-30  4.404
6    PRTY   2019-06-30  3.168
7    PRTY   2019-03-31  3.312
8   CPPRQ   2019-12-31  8.637
9   CPPRQ   2019-09-30  9.022
10  CPPRQ   2019-06-30  7.577
11  CPPRQ   2019-03-31  7.068
12   ETSY   2019-12-31  2.793
13   ETSY   2019-09-30  2.851
14   ETSY   2019-06-30  1.310
15   ETSY   2019-03-31  1.336
16      M   2019-12-31  2.320
17      M   2019-09-30  2.722
18      M   2019-06-30  2.284
19      M   2019-03-31  2.368
20    WMT   2019-12-31  2.075
21    WMT   2019-09-30  2.254
22    WMT   2019-06-30  2.243
23    WMT   2019-03-31  2.341

In [18]:
debt_equity_ticker_year('AMZN',2018)

  ticker calendardate     de
0   AMZN   2018-12-31  2.735
1   AMZN   2018-09-30  2.673
2   AMZN   2018-06-30  2.832
3   AMZN   2018-03-31  3.016

In [38]:
#Amazon CurrentRatio
all_amzn_cr = pd.DataFrame()
for y in [2018,2019,2020]:
    all_amzn_cr = all_amzn_cr.append(current_ratio_ticker_year('AMZN',y))
    
all_amzn_cr.set_index('calendardate',inplace=True)
all_amzn_cr.drop(columns='ticker',inplace=True)
all_amzn_cr.rename(columns={'currentratio':'AMZN'},inplace=True)
all_amzn_cr

               AMZN
calendardate
2018-12-31    1.098
2018-09-30    1.082
2018-06-30    1.072
2018-03-31    1.058
2019-12-31    1.097
2019-09-30    1.096
2019-06-30    1.102
2019-03-31    1.090
2020-09-30    1.108
2020-06-30    1.181
2020-03-31    1.079

In [37]:
#PRTY CurrentRatio
all_prty_cr = pd.DataFrame()
for y in [2018,2019,2020]:
    all_prty_cr = all_prty_cr.append(current_ratio_ticker_year('PRTY',y))
    
all_prty_cr.set_index('calendardate',inplace=True)
all_prty_cr.drop(columns='ticker',inplace=True)
all_prty_cr.rename(columns={'currentratio':'PRTY'},inplace=True)
all_prty_cr

               PRTY
calendardate
2018-12-31    1.439
2018-09-30    1.304
2018-06-30    1.274
2018-03-31    1.267
2019-12-31    1.287
2019-09-30    1.248
2019-06-30    1.225
2019-03-31    1.161
2020-09-30    1.187
2020-06-30    1.118
2020-03-31    1.150

               AMZN   PRTY  CPPRQ   ETSY      M    WMT
calendardate
2018-12-31    1.098  1.439  1.524  6.071  1.423  0.799
2018-09-30    1.082  1.304  1.576  5.491  1.345  0.810
2018-06-30    1.072  1.274  1.627  5.870  1.532  0.926
2018-03-31    1.058  1.267  1.729  6.616  1.519  0.734
2019-12-31    1.097  1.287  1.411  4.885  1.184  0.795
2019-09-30    1.096  1.248  1.515  6.114  1.281  0.811
2019-06-30    1.102  1.225  1.372  4.466  1.475  0.764
2019-03-31    1.090  1.161  1.509  4.870  1.416  0.773
2020-09-30    1.108  1.187  1.150  4.980  1.106  0.835
2020-06-30    1.181  1.118  1.218  4.272  1.160  0.793
2020-03-31    1.079  1.150  0.500  5.710  1.236  0.766

In [61]:
# All Current Ratio
all_cr = pd.concat([all_amzn_cr,all_prty_cr,all_cpprq_cr],axis=1,join ='inner',sort=True)
all_cr

               AMZN   PRTY    JCP
calendardate
2018-03-31    1.058  1.267  1.729
2018-06-30    1.072  1.274  1.627
2018-09-30    1.082  1.304  1.576
2018-12-31    1.098  1.439  1.524
2019-03-31    1.090  1.161  1.509
2019-06-30    1.102  1.225  1.372
2019-09-30    1.096  1.248  1.515
2019-12-31    1.097  1.287  1.411
2020-03-31    1.079  1.150  0.500
2020-06-30    1.181  1.118  1.218
2020-09-30    1.108  1.187  1.150

In [91]:
def current_ratio(ticker):
    all_cpprq_cr = pd.DataFrame()
    for y in [2018,2019,2020]:
        all_cpprq_cr = all_cpprq_cr.append(current_ratio_ticker_year(ticker,y))
    
    all_cpprq_cr.set_index('calendardate',inplace=True)
    all_cpprq_cr.drop(columns='ticker',inplace=True)
    all_cpprq_cr.rename(columns={'currentratio':ticker},inplace=True)
    return all_cpprq_cr

def current_ratio_agg(ticker_list):
    dflist = []
    for ticker in ticker_list:
        df = current_ratio(ticker)
        dflist.append(df)
    
    return pd.concat(dflist,axis=1)

current_ratio_agg(tickers)

               AMZN   PRTY  CPPRQ   ETSY      M    WMT
calendardate
2018-12-31    1.098  1.439  1.524  6.071  1.423  0.799
2018-09-30    1.082  1.304  1.576  5.491  1.345  0.810
2018-06-30    1.072  1.274  1.627  5.870  1.532  0.926
2018-03-31    1.058  1.267  1.729  6.616  1.519  0.734
2019-12-31    1.097  1.287  1.411  4.885  1.184  0.795
2019-09-30    1.096  1.248  1.515  6.114  1.281  0.811
2019-06-30    1.102  1.225  1.372  4.466  1.475  0.764
2019-03-31    1.090  1.161  1.509  4.870  1.416  0.773
2020-09-30    1.108  1.187  1.150  4.980  1.106  0.835
2020-06-30    1.181  1.118  1.218  4.272  1.160  0.793
2020-03-31    1.079  1.150  0.500  5.710  1.236  0.766